### ISSUE TITLE
feedback 

### ISSUE THREAD

**Issue by ezkemboi** [hoseakimutai/Todo-list#1]
In the following : 

1. Please separate the field for `title` and for `description`. The title is the input text and the description is the text area.
2. Make sure, validation is done. The title and description are required before  saving
3. What do `edit` and `delete` does with the add button? What do those do before adding an item? Only editing and deleting on the todo is the one required.
4. I am unable to edit an item when it does not have a title. 
5. Generally good work
<img width="1429" alt="Screenshot 2023-04-22 at 06 40 03" src="https://user-images.githubusercontent.com/48981919/233760590-5998f375-e26a-4e28-9f0c-bb34924bba24.png">

**Comment by hoseakimutai** [comment]
fixed sir

**Comment by ezkemboi** [comment]
I will take a look
